{% set name = "transbigdata" %}
{% set version = "0.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transbigdata-{{ version }}.tar.gz
  sha256: 58a0e93dc8001dc7fa8d05a4d10f1be1e38e1ea3e181cf7470e7e9257fee6fb7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - pandas
    - geopandas
    - shapely
    - scipy
    - matplotlib-base
    - python >=3.7

test:
  imports:
    - transbigdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ni1o1/transbigdata
  summary: A Python package developed for transportation spatio-temporal big data processing and analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ni1o1
