{% set name = "transbigdata" %}
{% set version = "0.4.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transbigdata-{{ version }}.tar.gz
  sha256: fe5f28a2075013a9279229a8819d1c3964d4974ce122031b9eff5e6cbada92a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - geopandas
    - shapely
    - scipy
    - matplotlib-base
    - python >=3.6

test:
  imports:
    - transbigdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ni1o1/transbigdata
  summary: A Python package developed for transportation spatio-temporal big data processing and analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ni1o1
